const jobsData = [
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Data Analyst',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Designer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Drupal Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Back-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Software Engineer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Solutions Architect',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Junior Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Data Scientist',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
]

export default jobsData
